# File: run.yaml
# Description: Configuration file for the course recommendation system with mastery levels
# Purpose: Configure RL models with clustering-based reward adjustment

# Data Paths
taxonomy_path: Data - Collection/Final/taxonomy.csv      # Path to skill taxonomy data
course_path: Data - Collection/Final/courses.json        # Path to course data
cv_path: Data - Collection/Final/resumes.json           # Path to learner profiles
job_path: Data - Collection/Final/jobs.json             # Path to job listings
mastery_levels_path: Data - Collection/Final/mastery_levels.json  # Path to skill mastery levels
results_path: Code/results                              # Directory for storing results
branch_name: clusteringRL-mastery-levels                # Branch name for organizing results

# Data Processing Parameters
level_3: true                                          # Use third level of taxonomy (true) or fourth level (false)
                                                       # True: fewer, more general skills
                                                       # False: more specific skills

# Dataset Size Parameters
nb_courses: 100                                        # Number of courses to include in the dataset
nb_cvs: -1                                            # Number of learner profiles to use (-1 for all)
max_cv_skills: 15                                     # Maximum number of skills per learner profile
nb_jobs: 100                                          # Number of jobs to include in the dataset

# Model Parameters
threshold: 0.8                                         # Minimum matching threshold for job eligibility
k: 2                                                  # Number of course recommendations to generate
model: dqn                                            # Reinforcement learning algorithm (ppo, dqn, a2c)
total_steps: 5000000                                # Total training steps
eval_freq: 1000                                       # Evaluation frequency during training
nb_runs: 1                                            # Number of independent runs
seed: 42                                              # Random seed for reproducibility

# Clustering Configuration
use_clustering: true                                  # Whether to use clustering for reward adjustment
auto_clusters: true                                   # Whether to automatically determine optimal number of clusters
max_clusters: 10                                      # Maximum number of clusters to try when using elbow method
n_clusters: 4                                         # Number of clusters for K-means clustering (used if auto_clusters=false)

# Reward Adjustment Multipliers
same_cluster_increase: 1.1                            # Multiplier for same cluster & reward increase
same_cluster_decrease: 0.9                            # Multiplier for same cluster & reward decrease
diff_cluster_increase: 1.3                            # Multiplier for different cluster & reward increase
diff_cluster_decrease: 0.8                            # Multiplier for different cluster & reward decrease



